---
AllCops:
  Exclude:
    - 'build/**/*'

Metrics/AbcSize:
  Max: 150 # 65

Metrics/ParameterLists:
  Max: 8

Metrics/LineLength:
  Max: 120

Metrics/BlockNesting:
  Max: 6

Metrics/ClassLength:
  Max: 180

Metrics/CyclomaticComplexity:
  Max: 50 # 15

Metrics/MethodLength:
  Max: 100 # 45

Metrics/PerceivedComplexity:
  Max: 22 # 15


Style/FormatString:
  EnforcedStyle: sprintf

Style/NegatedIf:
  Enabled: false

Style/NegatedWhile:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

# This is just so we don't have to correct a zillion lines
Style/StringLiterals:
  Enabled: false

# XXX ruby 1.8 compatibility
# Ruby 1.8 does't have each_with_object()
Style/EachWithObject:
  Enabled: false

# Ruby 1.8 requirement
Style/DotPosition:
  EnforcedStyle: trailing

# Ruby 1.8 requirement
Style/Lambda:
  Enabled: false

# Ruby 1.8 requirement
Style/HashSyntax:
  EnforcedStyle: hash_rockets

# in ruby1.8, proc {} is a synonym for lambda {}
# in ruby1.9, proc {} is a synonym for Proc.new {}
Style/Proc:
  Enabled: false

# This configuration was generated by `rubocop --auto-gen-config`
# on 2015-02-18 09:46:27 +0000 using RuboCop version 0.29.1.
# The point is for the user to remove these configuration records
# one by one as the offenses are removed from the code base.
# Note that changes in the inspected code, or installation of new
# versions of RuboCop, may require this file to be generated again.

# Offense count: 1
Lint/HandleExceptions:
  Enabled: false

# Offense count: 21
Lint/RescueException:
  Enabled: false

# Offense count: 23
# Cop supports --auto-correct.
Lint/UnusedBlockArgument:
  Enabled: false

# Offense count: 14
# Cop supports --auto-correct.
Lint/UnusedMethodArgument:
  Enabled: false

# Offense count: 27
Lint/UselessAssignment:
  Enabled: false

# Offense count: 7
Style/AccessorMethodName:
  Enabled: false

# Offense count: 1
Style/ClassAndModuleCamelCase:
  Enabled: false

# Offense count: 39
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  Enabled: false

# Offense count: 6
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassCheck:
  Enabled: false

# Offense count: 12
Style/ClassVars:
  Enabled: false

# Offense count: 16
# Cop supports --auto-correct.
Style/ColonMethodCall:
  Enabled: false

# Offense count: 4
# Configuration parameters: Keywords.
Style/CommentAnnotation:
  Enabled: false

# Offense count: 56
Style/Documentation:
  Enabled: false

# Offense count: 4
# Configuration parameters: AllowedVariables.
Style/GlobalVars:
  Enabled: false

# Offense count: 5
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Enabled: false

# Offense count: 2
# Configuration parameters: EnforcedStyle, MinBodyLength, SupportedStyles.
Style/Next:
  Enabled: false

# Offense count: 3
# Configuration parameters: NamePrefix, NamePrefixBlacklist.
Style/PredicateName:
  Enabled: false

# Offense count: 4
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/RaiseArgs:
  Enabled: false

# Offense count: 3
Style/RegexpLiteral:
  MaxSlashes: 3

# Offense count: 102
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SignalException:
  Enabled: false

# Offense count: 6
# Cop supports --auto-correct.
Style/SpecialGlobalVars:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: ExactNameMatch, AllowPredicates, AllowDSLWriters, Whitelist.
Style/TrivialAccessors:
  Enabled: false

# Offense count: 20
# XXX breaks in ruby 1.9
Lint/DeprecatedClassMethods:
  Enabled: false
