#!/usr/bin/ruby
$: << File.join(File.dirname(__FILE__), "..", "lib")

require 'provision/catalogue'

Provision::Catalogue::load('../lib/config')
build = Provision::Catalogue::build("vanillavm", {:hostname=>"myfirstmachine"})
build.execute()