dnsmasq \
--log-dhcp \
--dhcp-option option:router \
--dhcp-option option:dns-server,192.168.5.1 \
-s dev.net.local \
--strict-order \
--bind-interfaces \
--pid-file=/var/run/dnsmasq.pid \
--except-interface lo \
--interface br_mgmt \
--interface br_prod \
--dhcp-range 192.168.5.1,static \
--dhcp-range set:prod,192.168.6.100,192.168.6.254 \
--read-ethers \
--dhcp-no-override \
--log-queries
