#! /bin/sh -eu

REPOSITORY="$1"
DIRECTORY="$2"

[ -d "$DIRECTORY" ] || { echo "$DIRECTORY does not exist"; exit 1; }

SCRATCH=$(mktemp -d)
trap "rm -rf $SCRATCH" 0

git clone --no-checkout "$REPOSITORY" "$SCRATCH"
mv "$SCRATCH"/.git "$DIRECTORY"/
rmdir "$SCRATCH"

cd "$DIRECTORY"
git reset -q --hard HEAD

