define "sehub_trusty" do
  copyboot

  run('install rc.local') do
    selenium_deb_version = spec[:selenium_deb_version] || "1:2.53.1-1.0.1020"
    se_host = spec[:hostname]
    se_nodes = spec[:nodes].join(',')

    open("#{spec[:temp_dir]}/etc/rc.local", 'w') do |f|
      f.puts "#!/bin/sh -e\n" \
        "if [ -e /var/lib/firstboot ]; then exit 0; fi\n" \
        "echo 'Running rc.local' | logger\n" \
        "apt-get -y --force-yes update\n" \
        "/usr/sbin/adduser --disabled-password --no-create-home --gecos '' ci \n" \
        "apt-get -y --force-yes install zulu-8\n" \
        "sed -i'.bak' -e 's#^securerandom.source=.*#securerandom.source=file:/dev/./urandom#'" \
        " /usr/lib/jvm/zulu-8-amd64/jre/lib/security/java.security\n" \
        "apt-get -y --force-yes install selenium=#{selenium_deb_version}\n" \
        "apt-get -y --force-yes install selenium-hub\n" \
        "apt-get -y --force-yes install python-lxml\n" \
        "update-rc.d selenium-hub defaults\n" \
        "echo '[segrid]' > /etc/segrid.properties\n" \
        "echo 'segrid.filter=#{se_host}' >> /etc/segrid.properties\n" \
        "echo 'segrid.nodes=#{se_nodes}' >> /etc/segrid.properties\n" \
        "/etc/init.d/selenium-hub start\n" \
        "echo 'Generated by /etc/rc.local to mark that the first boot setup has been performed' > /var/lib/firstboot\n" \
        "echo 'Finished running rc.local'\n" \
        "exit 0\n"
    end
  end
end
