define "senode_trusty" do
  copyboot

  run('install rc.local') do
    selenium_version = spec[:selenium_version] || "2.32.0"
    firefox_version = spec[:firefox_version] || "11.0+build1-0ubuntu4"
    chrome_version = spec[:chrome_version] || "22.0.1229.79-r158531"
    se_host = spec[:selenium_hub_host]
    se_port = "7799"

    open("#{spec[:temp_dir]}/etc/rc.local", 'w') do |f|
      f.puts "#!/bin/sh -e\n" \
        "if [ -e /var/lib/firstboot ]; then exit 0; fi\n" \
        "echo 'Running rc.local' | logger\n" \
        "apt-get -y --force-yes update\n" \
        "/usr/sbin/adduser ci\n" \
        "apt-get -y --force-yes install zulu-8\n" \
        "sed -i'.bak' -e 's#^securerandom.source=.*#securerandom.source=file:/dev/./urandom#'" \
        " /usr/lib/jvm/zulu-8-amd64/jre/lib/security/java.security\n" \
        "apt-get -y --force-yes install acpid\n" \
        "apt-get -y --force-yes install xvfb\n" \
        "apt-get -y --force-yes install dbus\n" \
        "apt-get -y --force-yes install dbus-x11\n" \
        "apt-get -y --force-yes install hicolor-icon-theme\n" \
        "apt-get -y --force-yes install firefox=#{firefox_version}\n" \
        "ln -s /usr/lib/firefox/firefox /usr/bin/firefox-bin\n" \
        "apt-get -y --force-yes install google-chrome-stable=#{chrome_version}\n" \
        "apt-get -y --force-yes install selenium=#{selenium_version}\n" \
        "apt-get -y --force-yes install selenium-node\n" \
        "update-rc.d selenium-node defaults\n" \
        "echo 'HUBHOST=#{se_host}' > /etc/default/selenium-node\n" \
        "echo 'HUBPORT=#{se_port}' >> /etc/default/selenium-node\n" \
        "echo 'Generated by /etc/rc.local to mark that the first boot setup has been performed' > /var/lib/firstboot\n" \
        "echo 'Finished running rc.local'\n" \
        "exit 0\n"
    end
  end
end
